# Generated by Django 5.0.4 on 2024-05-01 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('summary', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('published_date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, default='placeholder.png', upload_to='announcement_thumbnails')),
            ],
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('summary', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('address_info', models.CharField(blank=True, max_length=50)),
                ('published_date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, default='placeholder.png', upload_to='benefit_thumbnails')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('preferences_notify_benefits', models.BooleanField(default=True)),
                ('preferences_notify_announcements', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
