# Generated by Django 5.0.4 on 2024-05-05 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userprofile_first_name_userprofile_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
